macos_commands = sorted(set([
    'afconvert', 'afinfo', 'afplay', 'airport', 'alias', 'alloc', 'apropos',
    'asr', 'atsutil', 'awk', 'basename', 'bash', 'bc', 'bg', 'bind', 'bless',
    'break', 'brew', 'builtin', 'bzip2', 'caffeinate', 'cal', 'calendar',
    'caller', 'cancel', 'case', 'cat', 'chflags', 'chgrp', 'chmod',
    'chown', 'chroot', 'chsh', 'cksum', 'clear', 'cmp', 'codesign', 'comm',
    'command', 'complete', 'continue', 'cp', 'cpio', 'createhomedir', 'cron',
    'crontab', 'csplit', 'csrutil', 'cupsfilter', 'cut', 'date', 'dc', 'dd',
    'declare', 'defaults', 'df', 'diff', 'diff3', 'dig', 'dirname', 'dirs',
    'diskutil', 'disown', 'ditto', 'dot_clean', 'drutil', 'dscacheutil',
    'dscl', 'dseditgroup', 'dsenableroot', 'dsmemberutil', 'du', 'echo', 'ed',
    'enable', 'env', 'eval', 'exec', 'execsnoop', 'exit', 'expand', 'expect',
    'export', 'expr', 'false', 'fc', 'fdesetup', 'fdisk', 'fg', 'file', 'find',
    'fmt', 'fold', 'for', 'fs_usage', 'fsck', 'ftp', 'function', 'fuser',
    'GetFileInfo', 'getopt', 'getopts', 'goto', 'grep', 'groups', 'gunzip',
    'gzip', 'halt', 'hash', 'head', 'hdiutil', 'history', 'host', 'hostname',
    'htop', 'iostat', 'iconv', 'id', 'if', 'ifconfig', 'info', 'install',
    'installer', 'iosnoop', 'jobs', 'join', 'keytool', 'kickstart', 'kill',
    'killall', 'kextfind', 'kextstat', 'kextunload', 'klist', 'last',
    'launchctl', 'leave', 'less', 'let', 'lipo', 'ln', 'locate', 'logname',
    'login', 'logout', 'look', 'lp', 'lpstat', 'lpr', 'lprm', 'ls', 'lsbom',
    'lsof', 'lsregister', 'man', 'md5', 'mdfind', 'mdimport', 'mdls', 'mdutil',
    'mkdir', 'mkfifo', 'mkfile', 'mktemp', 'more', 'mount', 'msgs', 'mtree',
    'mv', 'nano', 'nc', 'net', 'netstat', 'networkQuality', 'networksetup',
    'nice', 'nl', 'nohup', 'ntfs.util', 'nvram', 'onintr', 'open', 'opensnoop',
    'openssl', 'osascript', 'osacompile', 'passwd', 'paste', 'pbcopy', 'pbpaste',
    'pbs', 'pdisk', 'pgrep', 'ping', 'pkill', 'pkgbuild', 'pkgutil', 'plutil',
    'pmset', 'popd', 'pr', 'printenv', 'printf', 'profiles', 'ps', 'purge',
    'pushd', 'pwd', 'qlmanage', 'quota', 'rcp', 'read', 'readonly', 'reboot',
    'return', 'rev', 'rm', 'rmdir', 'rsync', 'say', 'screen', 'screencapture',
    'scselect', 'scutil', 'sdiff', 'security', 'sed', 'select', 'seq',
    'serverinfo', 'set', 'setfile', 'sharing', 'shasum', 'shift', 'shopt',
    'shortcuts', 'shutdown', 'sips', 'sleep', 'softwareupdate', 'sort', 'source',
    'spctl', 'split', 'sqlite3', 'srm', 'stat', 'stop', 'su', 'sudo', 'sum',
    'suspend', 'sw_vers', 'sysctl', 'system_profiler', 'systemsetup', 'tab2space',
    'tabs', 'tail', 'tar', 'taskpolicy', 'tccutil', 'tcpdump', 'tee', 'test',
    'textutil', 'time', 'times', 'tmutil', 'top', 'touch', 'tr', 'trap',
    'traceroute', 'traceroute6', 'trimforce', 'true', 'tty', 'type', 'ufs.util',
    'ulimit', 'umask', 'umount', 'unalias', 'uname', 'unexpand', 'uniq', 'units',
    'unset', 'until', 'uptime', 'users', 'uuidgen', 'uucp', 'vi', 'w', 'wait',
    'wait4path', 'wall', 'wc', 'whatis', 'whereis', 'which', 'while', 'who',
    'whoami', 'write', 'xargs', 'xattr', 'xcode-select', 'xxd', 'yes', 'zcat',
    'zip'
]))

custom_commands = ['flipper', 'clear', 'help', 'exit', 'cd', 'newtab', 'ssh']

commands = macos_commands + custom_commands